# permissions for end users to view adminnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminnetworkpolicy-viewer-role
rules:
- apiGroups:
  - policy.networking.k8s.io.policy.networking.k8s.io
  resources:
  - adminnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.networking.k8s.io.policy.networking.k8s.io
  resources:
  - adminnetworkpolicies/status
  verbs:
  - get
