# permissions for end users to edit adminnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminnetworkpolicy-editor-role
rules:
- apiGroups:
  - policy.networking.k8s.io.policy.networking.k8s.io
  resources:
  - adminnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.networking.k8s.io.policy.networking.k8s.io
  resources:
  - adminnetworkpolicies/status
  verbs:
  - get
