apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: kcp-workspaces-example
spec:
  priority: 100
  subject:
    namespaces:
      matchExpressions: {key: "workspace"; operator: Exists}
  ingress:
    - action: Deny
      from:
      - namespaces:
          notSameLabels:
          - workspace
    - allow: Allow
      to: 
      - namespaces:
          namespaceSelector:
            matchLabels: 
              kubernetes.io/metadata.name: sidecar-ns
          podSelector:
            matchLabels: 
              app: dns
    - allow: Allow
      to: 
      - namespaces:
          namespaceSelector:
            matchLabels: 
              kubernetes.io/metadata.name: monitoring-ns
          podSelector:
            matchLabels: 
              app: monitoring
              app: logginggit 
    