# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml
- experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
